name: Test PHP

on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  phplint:
    name: Phplint
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'
          extensions: simplexml
          tools: composer:v1
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Install composer
        run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest
      - name: Run PHPCS
        run: composer run lint
  phpunit:
      name: Phpunit
      runs-on: ubuntu-22.04
      services:
        mysql:
          image: mysql:5.7
          env:
            MYSQL_ROOT_PASSWORD: root
          ports:
            - 3306/tcp
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      steps:
        - name: Setup PHP version
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.2'
            extensions: simplexml, mysql
            tools: phpunit:7.5.15
        - name: Checkout source code
          uses: actions/checkout@master
        - name: Install WordPress Test Suite
          run: |
            bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:${{ job.services.mysql.ports['3306'] }} 5.2.2
        - name: Install composer
          run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest --no-dev
        - name: Run phpunit
          run: phpunit